### ISSUE TITLE
v0.6.8编辑后无法自动跳转到显示界面

### ISSUE THREAD

**Issue by GuojieLin** [zmister2016/MrDoc#102]
在v0.6.7，编辑时右上角显示的时发布。发布成功会提示并跳转到显示界面。
更新到v0.6.8以后，编辑时右上角显示的是保存，不是发布。保存完不会自动跳转到显示界面。
![图片](https://user-images.githubusercontent.com/9709432/123913261-9445b580-d9b0-11eb-9195-12a37ec2852a.png)

**Comment by zmister2016** [comment]
@GuojieLin 从 0.6.8 版本开始，修改文档页面「保存」按钮的含义是更新文档内容但是不修改文档状态。

**Comment by GuojieLin** [comment]
> 
> 
> @GuojieLin 从 0.6.8 版本开始，修改文档页面「保存」按钮的含义是更新文档内容但是不修改文档状态，且保存成功后不会进行页面跳转。

个人感觉从使用习惯上保存完大多数情况还是希望跳转到页面吧

**Comment by zmister2016** [comment]
> > @GuojieLin 从 0.6.8 版本开始，修改文档页面「保存」按钮的含义是更新文档内容但是不修改文档状态，且保存成功后不会进行页面跳转。
> 
> 个人感觉从使用习惯上保存完大多数情况还是希望跳转到页面吧

@GuojieLin 恰恰相反，更多的人反馈的是不期望跳转，一方面不便于保存文档后继续编辑，另一方面跳转会导致浏览器标签页越来越多，体验极差
