### ISSUE TITLE
搜索报错

### ISSUE THREAD

**Issue by ghostman-git** [zmister2016/MrDoc#104]
![image](https://user-images.githubusercontent.com/13376074/125220081-aef52400-e2f8-11eb-9eb2-067e66b47e91.png)

**Comment by zmister2016** [comment]
@ghostman-git 已知悉，感谢反馈

**Comment by zmister2016** [comment]
@ghostman-git 最新代码已修复，将归版至0.6.9

**Comment by zmister2016** [comment]
@ghostman-git 0.6.9 版本已修复
