### ISSUE TITLE
markdown将字符:m:解析成emoji图片

### ISSUE THREAD

**Issue by GuojieLin** [zmister2016/MrDoc#106]
![image](https://user-images.githubusercontent.com/9709432/125888894-a46464de-3a05-4234-85e8-08684583c937.png)

如上图：会将字符:M:解析为emoji图片，显示异常。 

![image](https://user-images.githubusercontent.com/9709432/125889047-be0b6719-9525-4669-9afb-60d6de89a8a7.png)

比如我需要输入日期格式 `yyyy:MM:dd` , 这时候就会解析异常

![image](https://user-images.githubusercontent.com/9709432/125889544-25bbcde8-b757-49d8-94f5-65060cff838a.png)

将字符串用于``
包裹或加粗都不行。只能用``` ````代码块进行包裹才能显示正常

![image](https://user-images.githubusercontent.com/9709432/125889565-dda7c259-f4f9-4d9f-948e-cb5abdc1258e.png)

**Comment by zmister2016** [comment]
@GuojieLin 已知悉，感谢反馈

**Comment by zmister2016** [comment]
@GuojieLin 最新代码的 editormd 编辑器已取消 Markdown 的 emoji 语法
