### ISSUE TITLE
图片上传后缀大小写问题

### ISSUE THREAD

**Issue by brookzhcn** [zmister2016/MrDoc#11]
app_doc/util_upload_img.py 中的img_upload函数
`
    if file_suffix.lower() not in allow_suffix:
        return {"success": 0, "message": "图片格式不正确"}
`
上传过程问有些图片的后缀是大写，也需要支持。

**Comment by zmister2016** [comment]
@brookzhcn  好的，感谢反馈，晚点进行修复

**Comment by zmister2016** [comment]
最新代码中已修复此问题，再次谢谢你的反馈
