### ISSUE TITLE
文檔回收桶Server Error (500)

### ISSUE THREAD

**Issue by jayhsia1997** [zmister2016/MrDoc#114]
MrDoc版本：0.6.9
問題：上級文檔從回收桶物理刪除，文檔回收桶會回Server Error (500)

**Comment by zmister2016** [comment]
@jayhsia1997 感谢反馈，稍后测试

**Comment by zmister2016** [comment]
@jayhsia1997 这边在本地和演示站点（http://mrdoc.zmister.com）测试均未发现问题，可以看看`log`目录下的`error.log`错误日志信息
