### ISSUE TITLE
修改附件大小限制不生效

### ISSUE THREAD

**Issue by graysonwp** [zmister2016/MrDoc#115]
现在要上传一个85M左右的附件，已经在站点设置中将附件大小限制修改为100M，并已经重启了应用程序，但是当上传该附件时，仍然会提示“文件不能超过48.83MB”。
<img width="1280" alt="2021-08-25_10-36-14" src="https://user-images.githubusercontent.com/22250741/130717566-aab11e0d-8f21-4aa1-9da4-594640ac5822.png">
<img width="1280" alt="2021-08-25_10-37-28" src="https://user-images.githubusercontent.com/22250741/130717578-8c989da2-c2ed-4996-af52-bdd4e1d0e527.png">

**Comment by zmister2016** [comment]
@graysonwp 感谢反馈，修复后将归版至0.7.1

**Comment by zmister2016** [comment]
@graysonwp 最新代码已修复，将归版至0.7.1

**Comment by graysonwp** [comment]
收到，感谢作者辛勤付出
