### ISSUE TITLE
能不能新增文件夹同步

### ISSUE THREAD

**Issue by hyhy01** [zmister2016/MrDoc#117]
例如有个markdown的文件夹，检测到变化就按照目录结构自动更新数据库。不需要手动导入mardown文件。
同时如果数据库变化，就同步更新这个文件夹内容

**Comment by hyhy01** [comment]
还有就是和git仓库进行同步

**Comment by zmister2016** [comment]
@hyhy01 MrDoc 提供了基于用户token的API，你可以自行编写本地程序监控文件变化然后进行文档编写或更新
