### ISSUE TITLE
修改文档排序后不生效

### ISSUE THREAD

**Issue by graysonwp** [zmister2016/MrDoc#122]
文档排序 修改并保存后 显示 保存排序成功，但是页面仍是原来的排序，配置页面刷新后也是原来的排序，相当于文档排序修改后没有生效。

https://user-images.githubusercontent.com/22250741/132988037-d5f2406c-d1cd-4329-9765-627e109b59f0.mov

**Comment by zmister2016** [comment]
@graysonwp 感谢反馈，已定位问题，修复后将归版至0.7.1

**Comment by zmister2016** [comment]
@graysonwp 最新代码已修复，将归版至 0.7.1

**Comment by graysonwp** [comment]
收到，感谢作者的辛勤付出。
