### ISSUE TITLE
editorMD编辑器,markdown流程图使用 parallel 标签会混乱

### ISSUE THREAD

**Issue by fangxia-** [zmister2016/MrDoc#124]
```flow
st=>start: 开始
e=>end: 结束
op1=>operation: 作业1
sub1=>subroutine: 子程序
cond=>condition: Yes or No?
io=>inputoutput: 输入输出
para=>parallel: 并行任务
st->op1->cond
cond(yes)->io->e
cond(no)->para
para(path1, bottom)->sub1(right)->op1
para(path2, top)->op1
st@>op1({"stroke":"Red"})@>cond({"stroke":"Red"})@>para({"stroke":"Red","stroke-width":4,"arrow-end":"classic-wide-long"})@>sub1({"stroke":"Red"})@>e({"stroke":"Red"})
```
以上在http://flowchart.js.org/ 官网渲染正常

<img width="991" alt="Snipaste_2021-10-15_11-35-03" src="https://user-images.githubusercontent.com/10776831/137428585-a520b7da-8249-4488-9ad1-308c7978503b.png">
但在本地编辑器中效果会把所有图标叠加到一起

![11111](https://user-images.githubusercontent.com/10776831/137428760-1a479c56-2e17-4022-aa2e-5958c8d462c5.png)
是版本问题吗?

**Comment by zmister2016** [comment]
@fangxia- 感谢反馈，后续将进行测试复现和修复

**Comment by zmister2016** [comment]
@fangxia- 最新代码已通过更新 flowchart.js 版本修复此问题，将归版至 0.7.5
