### ISSUE TITLE
文本和按钮错误

### ISSUE THREAD

**Issue by YHYJ** [zmister2016/MrDoc#126]
在“新建文集”的时候弹出的操作框中的提示是“*在可个人中心对文集权限进行进一步控制“，应该是“可在”

如图：

![11121](https://user-images.githubusercontent.com/21995281/143515899-b7abf5ea-0de2-4d37-9cf8-a68bf692afd7.png)

红圈里的按钮'<'以及另一半'>'是返回/前进么？按了没反应

**Comment by zmister2016** [comment]
@YHYJ 最新代码已修复文本错误，将归版至0.7.4
