### ISSUE TITLE
一些bug反馈

### ISSUE THREAD

**Issue by fcmxmk** [zmister2016/MrDoc#131]
## 1. 启动很快, 关闭需要非常久;

![image](https://user-images.githubusercontent.com/24162498/153843158-a5f84170-e9c5-468b-96a8-9fd67bbc40ea.png)

## 2. 搜索不存在的字符串正常, 搜索存在的字符串就会报 500 错误;

![image](https://user-images.githubusercontent.com/24162498/153843522-83ef5080-d0a8-4c7b-a65b-1b6248e06aad.png)

![image](https://user-images.githubusercontent.com/24162498/153843350-896955fe-ab79-45f1-9fae-3167c5872808.png)

> 后端日志: 

![image](https://user-images.githubusercontent.com/24162498/153843789-217c9c80-8ab2-4fb9-8998-5604ffcf6370.png)

> 程序版本信息

```
MrDoc 0.7.4

aiocontextvars==0.2.2
beautifulsoup4==4.8.2
certifi==2021.10.8
chardet==3.0.4
cobble==0.1.3
colorama==0.4.4
configparser==5.2.0
contextvars==2.4
crayons==0.4.0
Django==2.2.24
django-haystack==3.1.1
djangorestframework==3.11.2
idna==2.10
immutables==0.16
importlib-metadata==4.8.2
jieba==0.42.1
loguru==0.4.1
lxml==4.6.4
mammoth==1.4.13
Markdown==3.3.3
markdownify==0.6.0
packaging==21.3
Pillow==8.4.0
pyparsing==3.0.6
pytz==2021.3
PyYAML==5.4.1
requests==2.24.0
selenium==3.141.0
setuptools-scm==6.3.2
six==1.16.0
soupsieve==2.3.1
sqlparse==0.4.2
tomli==1.2.2
typing_extensions==4.0.1
urllib3==1.25.11
uWSGI==2.0.20
webdriver-manager==3.3.0
Whoosh==2.7.4
zipp==3.6.0
```

**Comment by fcmxmk** [comment]
mrdoc 程序升级到`MrDoc 0.7.4`, 上面提到的问题依然存在.

**Comment by fcmxmk** [comment]
## 问题 2 已经解决

原因是因为`代码块`内包含了以下代码

```
re.compile('\d+(?=[a-z]+)').findall(xx)
re.compile(r"\d+(?![a-z]+)").findall(xx)
re.compile(r"(?<=[a-z])\d+").findall(xx)
re.compile(r"(?<![a-z])\d+").findall(xx)
re.compile(r"(?:\d+)").findall(xx)
```

准确说是因为`代码块`内包含了下面这行代码
```
re.compile(r"(?<![a-z])\d+").findall(xx)
```

删掉这行代码就行了, 奇怪的bug.

> 补充
问题是发生在 `nginx + uwsgi + mrdoc`, 如果是直接使用 `pycharm` 启动 `mrdoc`, 就不会触发这个 bug

**Comment by zmister2016** [comment]
最新代码已修复文档搜索部分情况下500的问题

**Comment by fcmxmk** [comment]
- 文档中存在 `$*` 和 `$?` 这两个字符串, 且搜索这两个字符串时, 会报 500 错误;
- 在搜索`$#`时, 切换'全文搜索'和'精准搜索', 搜索框中的内容会变成`$`, 且结果也会同步变为只搜索`$`;
