### ISSUE TITLE
个人中心文档管理页面有bug

### ISSUE THREAD

**Issue by xkymf** [zmister2016/MrDoc#140]
![image](https://user-images.githubusercontent.com/102467968/168081268-e3f3a9d5-20e8-4324-81d5-9e81ab7b59e0.png)
表格中文档名称无法正常显示

**Comment by zmister2016** [comment]
描述清楚

**Comment by xkymf** [comment]
麻烦大佬了，这应该是前端页面的小问题，我稍微修改了一下括号格式又恢复正常了，所以不用麻烦了，其实就是个人中心里面的文档管理里的表格文档名称显示成{d.name}，可能是我pycharm的原因

**Comment by xkymf** [comment]
麻烦大佬了，这应该是前端页面的小问题，我稍微修改了一下括号格式又恢复正常了，所以不用麻烦了，其实就是个人中心里面的文档管理里的表格文档名称显示成{d.name}，可能是我pycharm的原因
