### ISSUE TITLE
使用一段时间后2个python进程cpu占用100%，docker模式部署，jonnyan404/mrdoc:0.7.8和zmister/mrdoc:v3都有此问题。

### ISSUE THREAD

**Issue by zhangxinlun** [zmister2016/MrDoc#143]
使用一段时间后2个python进程cpu占用100%，docker模式部署，jonnyan404/mrdoc:0.7.8和zmister/mrdoc:v3都有此问题。数据库使用mysql，mysql导出后大小400m左右

以下进程间歇性100%
python /app/MrDoc/manage.py rebuild_index
以下进程长时间100%
python -u /app/MrDoc/manage.py runserver --noreload 0.0.0.0:10086

现在用的是开源版，请问专业版是否有此问题？

**Comment by zmister2016** [comment]
开源版、专业版均无此问题反馈

**Comment by Jonnyan404** [comment]
貌似是`表格组件`的问题,建议改用富文本的表格处理.
