### ISSUE TITLE
目录定位有bug

### ISSUE THREAD

**Issue by dalamudx** [zmister2016/MrDoc#147]
目前发现一个文档里的两个概述链接一样，会导致点击toc目录里的第二个概述自动跳转到第一个概述那里去
第一个概述的链接
![image](https://user-images.githubusercontent.com/88395653/178131670-0a6da9e2-eb12-4a65-b8d4-df181864889a.png)
第二个概述的链接
![image](https://user-images.githubusercontent.com/88395653/178131730-1a185bda-df3f-47ba-97a0-0712f39d0fe1.png)

**Comment by zmister2016** [comment]
目前按文档标题进行目录定位，同名标题只会跳转到第一个
