### ISSUE TITLE
Why？为什么中英文混杂？

### ISSUE THREAD

**Issue by DeathAndLife** [zmister2016/MrDoc#149]
![image](https://user-images.githubusercontent.com/51323917/182388870-3196405f-635b-41c8-b969-fc298598fe4e.png)
![image](https://user-images.githubusercontent.com/51323917/182388943-391aaa42-f9c6-4717-a6df-22fa4205916b.png)

**Comment by zmister2016** [comment]
浏览器的语言 preference 将「中文」设为第一个

**Comment by DeathAndLife** [comment]
> 

嗯，可以！之前改过，估计缓存问题 没生效
不过还是**建议**首台管理增加一个**语言选择**的选项

另外还有一些使用过程中的**建议**
**对于宽屏用户**
- 首页两边留白太宽
- 整体字体偏小
