### ISSUE TITLE
语法高亮有问题，是我用法不对吗？

### ISSUE THREAD

**Issue by sw554227643** [zmister2016/MrDoc#150]
![image](https://user-images.githubusercontent.com/44052801/187632027-7d70a933-318e-42d5-bcd3-5cd6a4db2276.png)
![image](https://user-images.githubusercontent.com/44052801/187632092-a497802b-b627-4d97-b876-22f84dadc648.png)
可以看到并没有高亮

**Comment by zmister2016** [comment]
指定语言，三引号后指定语言
