### ISSUE TITLE
docker 运行容器报错sh: can't open 'docker_mrdoc.sh': No such file or directory

### ISSUE THREAD

**Issue by hejunjie** [zmister2016/MrDoc#154]
使用windows的docker desktop部署环境， 运行容器报错sh: can't open 'docker_mrdoc.sh': No such file or directory

![image](https://user-images.githubusercontent.com/12097125/202588960-fa62c339-f58d-4302-9596-f0fd3ae9b130.png)

**Comment by zmister2016** [comment]
zmister/mrdoc Docker镜像需要挂载本地代码目录使用，详见：https://doc.mrdoc.pro/doc/3958/

**Comment by windnemo** [comment]
Windwos10下的docker有可能使用的wsl运行的，也就是说docker程序运行在Windows自带的linux虚拟机上，那么目录就不相同了，/mnt/d/opt 就表示的D盘下opt目录。

**Comment by mwnu** [comment]
> [@hejunjie](https://github.com/hejunjie) zmister/mrdoc Docker镜像需要挂载本地代码目录使用，详见：https://doc.mrdoc.pro/doc/3958/
realpath() of /app/MrDoc/config/uwsgi.ini failed: No such file or directory [core/utils.c line 3640]
脚本中使用的是v1版的docker-compose，我装了之后还是启动不了。
我以为是镜像的问题。
