### ISSUE TITLE
C 语言的代码块发布后无法高亮显示

### ISSUE THREAD

**Issue by yangchaohe** [zmister2016/MrDoc#155]
版本：开源版 0.8.4

在 EditorMD 下编辑
![image](https://user-images.githubusercontent.com/58938416/202893008-6e70fe53-be66-422e-a2c6-abb3ab740302.png)
预览高亮正常
![image](https://user-images.githubusercontent.com/58938416/202893042-5b21b8fa-bc7d-41ad-a7c7-f4f4b1712ac7.png)
发布后查看高亮异常
![image](https://user-images.githubusercontent.com/58938416/202893064-530e5efb-25e2-4db1-96a9-8c6e9c192e99.png)

目前测试 java php python 高亮都正常，只有 c 语言出现这种情况。

**Comment by zmister2016** [comment]
最新代码已重构Markdown渲染器，支持所述代码高亮
