### ISSUE TITLE
jonnyan404 的docker镜像咋不更新了？

### ISSUE THREAD

**Issue by ghostman-git** [zmister2016/MrDoc#156]
jonnyan404 的docker镜像咋不更新了？

**Comment by Jonnyan404** [comment]
并不是不更新,
是更新了使用教程,
需要用户手动操作,
可以不依赖镜像的更新.
具体请参考 https://www.mrdoc.fun/doc/18/  中关于手动升级部分.

**Comment by lazzman** [comment]
手动升级：进入容器内，执行`git pull`，重启容器即可。
