### ISSUE TITLE
批量导入文集失败

### ISSUE THREAD

**Issue by PlayWithSanLei** [zmister2016/MrDoc#157]
版本0.8.5

部署在腾讯云	Ubuntu Server 20.04 LTS 64bit 通过一键部署脚本

然后管理员在个人中心导入文集 markdown压缩包的时候没数据，就是个空文集

这个是文集目录结构，是导出来的
<img width="242" alt="截屏2022-12-07 12 38 18" src="https://user-images.githubusercontent.com/63458338/206089779-552ca2a6-7965-4477-a021-12b0bbd263c7.png">

这个怎么处理呀，我看之前的issue有大佬导入成功的

**Comment by PlayWithSanLei** [comment]
测试部署在docker上也不行

**Comment by zmister2016** [comment]
@PlayWithSanLei 文集导入已由单独的程序提供，详见 https://gitee.com/zmister/mrdoc-import-toolbox/releases
