### ISSUE TITLE
希望能让官方镜像增加对arm64的支持

### ISSUE THREAD

**Issue by zhoujun0601** [zmister2016/MrDoc#158]

**Comment by euzenlee** [comment]
自己按文件中的Dockerfile自建一个镜像即可。
下载 Dockerfile，docker_mrdoc.sh ， requirements.txt到 arm64设备的某个目录中，修改一下Dockerfile，去掉 && python -m pip install --upgrade pip \ 这一行。执行docker build 即可，约10分钟左右可以建成。

**Comment by zmister2016** [comment]
官方镜像已支持ARM64
