### ISSUE TITLE
删除用户bug

### ISSUE THREAD

**Issue by songjh513** [zmister2016/MrDoc#159]
删除用户，其所创建文档就会归属到文集创建者下；
但是被删除用户创建的文集，整个都没了；通过新建一个文集，手动改app_doc_project 的 id 能把在这个文集下的其他用户的文档恢复回来，但是被删除用户的文档就找不到了，有没什么办法？

**Comment by zmister2016** [comment]
删除用户时理应删除用户创建的文集、文档，最新代码已修复删除不全的问题。
