### ISSUE TITLE
后台页面和个人页面显示异常

### ISSUE THREAD

**Issue by ispace-top** [zmister2016/MrDoc#163]
#### 环境版本：
- 官方Docker镜像 V5版本；
- MrDoc 0.8.7 
#### 服务器环境：
- 前端Nginx服务器做二级域名转发至MrDoc容器端口
- https由Nginx配置有全局泛域名证书。
#### 打开后台页面和个人页面出现如下场景（文档功能正常）：
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/13082103/223059413-ec14c15b-0ae0-4a9a-890e-ce3d4ec5acbf.png">
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/13082103/223059451-32c262ea-180e-40de-8c42-1717cb019791.png">

**Comment by zmister2016** [comment]
![image](https://user-images.githubusercontent.com/42526859/223100235-d3471ad7-f76a-444d-958f-3c254928fb5c.png)

检查 Nginx 的 X-Frame-Options 配置项，MrDoc 自身已设置，不需要再通过 Nginx 配置。

**Comment by ispace-top** [comment]
抱歉，今天新域名备案通过了，已切换到新域名：https://doc.ispace.top。
昨天晚上找到问题原因了：
在conf.ini中配置X-Frame-Options 后，并不会移除原有的X-Frame-Options 属性，导致出现属性冲突了。
我不太懂前端知识，只好在Nginx强制替换了X-Frame-Options 配置就好了。
具体解决过程和错误信息可以参考下我的记录：https://doc.ispace.top/doc/2/。
