### ISSUE TITLE
短词语搜索不出来

### ISSUE THREAD

**Issue by goldroad** [zmister2016/MrDoc#169]
搜索MSVCR110有结果
![image](https://github.com/zmister2016/MrDoc/assets/60783345/6c58b2d3-5ba8-41a5-a4af-b61eea4075f7)

搜索MSVCR11以及更短词语，都搜不出来
![image](https://github.com/zmister2016/MrDoc/assets/60783345/e316fcd5-73f4-4b07-85c4-a2b7b9577f35)

**Comment by zmister2016** [comment]
切换精准搜索

**Comment by goldroad** [comment]
免费版不支持这个功能吗？
