### ISSUE TITLE
关于文库超多文集的bug

### ISSUE THREAD

**Issue by ad-calcium** [zmister2016/MrDoc#171]
当一个文集的文章很多，每次点击一个文章，左边的目录就会刷新，一下子就会请求很多数据，响应也会慢一些，服务器负载也会重一些
![WQV2U{8U0DU$J~V4HMZ20S5](https://github.com/zmister2016/MrDoc/assets/33044636/552f8304-414a-4b15-8547-99beeda570e8)

**Comment by zmister2016** [comment]
@ad-calcium 最新代码已优化，当文集文档超过999时，文集大纲启用异步分页加载
