### ISSUE TITLE
http正常，但是用https刷不出来大纲

### ISSUE THREAD

**Issue by wbsu2003** [zmister2016/MrDoc#19]
在群呼上用docker搭建，在局域网用ip访问创建了几个文件，后用fpr映射到公网，用域名访问发现https协议时不能正常获取到文档的大纲。

用 https 时无法正常获取大纲

![title](https://raw.githubusercontent.com/wbsu2003/gitnote-images/master/mynote/2020/08/02/1596365111271-1596365111272.png)

但是用 http 是正常获的

![title](https://raw.githubusercontent.com/wbsu2003/gitnote-images/master/mynote/2020/08/02/1596365074831-1596365074834.png)

**Comment by zmister2016** [comment]
@wbsu2003 建议用源码安装部署试一试

**Comment by chinobing** [comment]
应该与https无关，我在demo的网站也试过好几次大纲加载失败

**Comment by chinobing** [comment]
![image](https://user-images.githubusercontent.com/27722028/91940864-c6ec3680-ed2a-11ea-9c01-30a3183aa103.png)
![image](https://user-images.githubusercontent.com/27722028/91940888-d4092580-ed2a-11ea-975b-e3a02d3befbc.png)
![image](https://user-images.githubusercontent.com/27722028/91941028-1a5e8480-ed2b-11ea-94e2-20a249fd05a2.png)

会不会是CSRF的问题导致？

[django 1.10 CSRF验证失败的解决过程](https://www.cnblogs.com/Rocky_/p/6140362.html)


对了，为啥q群给钱都不能进 -.-

**Comment by zmister2016** [comment]
这个问题应该可以完结了
