### ISSUE TITLE
是不是可以添加一个Dockerfile方便部署

### ISSUE THREAD

**Issue by pigeonligh** [zmister2016/MrDoc#20]
如题

**Comment by zmister2016** [comment]
@pigeonligh 有朋友制作了docker版本镜像，dockerHub的地址为https://hub.docker.com/r/jonnyan404/mrdoc-nginx，使用方式详见http://mrdoc.zmister.com/project-7/doc-270/

**Comment by pigeonligh** [comment]
> @pigeonligh 有朋友制作了docker版本镜像，dockerHub的地址为https://hub.docker.com/r/jonnyan404/mrdoc-nginx
> 使用方式详见http://mrdoc.zmister.com/project-7/doc-270/

好的！谢谢
