### ISSUE TITLE
关于新功能和贡献的疑问

### ISSUE THREAD

**Issue by zhongjiajie** [zmister2016/MrDoc#26]
* 新功能：看到公众号说有tag功能，但是没有在commit历史中没有看到对应的commit，请问是还没有release么？
* 我们这边有在使用mrdoc作为文档共享工具，修改了部分bug，不知道这边对于PR的接收程度是如何的？

**Comment by zmister2016** [comment]
@zhongjiajie 标签功能在0.5.8版本内上线，没有体现在commit说明里面，具体详见更新日志。PR的话，得综合考虑一下现有版本规划的功能。

**Comment by zhongjiajie** [comment]
那这边提PR的话是否欢迎呢？或者说是直接子github开issue沟通还是别的方式沟通。在issue的话我会先开issue，然后PR关联到issue

**Comment by zmister2016** [comment]
> 那这边提PR的话是否欢迎呢？或者说是直接子github开issue沟通还是别的方式沟通。在issue的话我会先开issue，然后PR关联到issue @ zmister2016

沟通的话，现在主要是在QQ群，提Issue、提PR都欢迎。
