### ISSUE TITLE
删除用户时，参与过的协作文档也一起删掉

### ISSUE THREAD

**Issue by ghostman-git** [zmister2016/MrDoc#29]
企业用，如果有离职，删掉用户，也会把参与协作的文档一并删掉不太友好

**Comment by zmister2016** [comment]
@ghostman-git 嗯，目前确实存在这个问题，下次版本更新连同文集转让功能一同优化。感谢反馈！

**Comment by zmister2016** [comment]
自0.6.2版本始，删除用户时，用户的协作文档将会转让给文集所有者

**Comment by ghostman-git** [comment]
> 自0.6.2版本始，删除用户时，用户的协作文档将会转让给文集所有者

但是，删除用户后，用户所创建的协作文档也一并被删除了的

**Comment by MrNiebit** [comment]
> > 自0.6.2版本始，删除用户时，用户的协作文档将会转让给文集所有者
> 
> 但是，删除用户后，用户所创建的协作文档也一并被删除了的

这种有办法恢复吗？文集是物理删除还是逻辑删除呀
