### ISSUE TITLE
设置可见和协作权限时，更快捷地选择用户

### ISSUE THREAD

**Issue by LyleC** [zmister2016/MrDoc#32]
比如我用一个普通权限的账户创建的文集，如果要设置可见和协作，似乎只能按照用户名一个个手动添加。  
而问题在于普通账户又看不到后台的用户列表，很痛苦。

比较理想的是，管理员账号能够在后台给用户分组，设置组织或者角色。然后设置可见和协作时，能够统一添加。  
或者权宜之计是，在添加用户时，能够按已经输入的字母去搜索匹配，然后点选。  
目前添加可见时，似乎添加的用户不存在也可以设置通过，而添加协作时，最后会检查一下合法性，不存在的用户无法添加，不太清楚内部的逻辑是怎样的。

**Comment by zmister2016** [comment]
@LyleC 嗯，目前版本不会做用户分组。后续版本在文集设置协作和权限的时候，会像文集转让一样，显示可搜索的用户列表输入框，大概在这个月或下个月的更新实现。感谢反馈！

**Comment by zmister2016** [comment]
0.6.1 版本已支持从用户列表中选择用户
