### ISSUE TITLE
如何连接数据库

### ISSUE THREAD

**Issue by zyy2721** [zmister2016/MrDoc#33]
您好，我们近期需要对所有人提交的文档做一个统计，想咨询一下，数据库连接信息是多少呢？
或者觅道有计划做统计报表功能吗？可以统计周期内每个人提交的文档数量之类的。

**Comment by zmister2016** [comment]
@zyy2721 如果使用的默认配置，数据库就是SQLITE，其数据库文件位于/MrDoc/config/db.sqlite，可以使用SQLTE expert等工具连接打开即可。统计报表功能可以放在开发备忘录里面。

**Comment by zyy2721** [comment]
请问能否直连数据库？ 如果是把数据库文件拷出来的话，就无法查看到实时的数据展示。
