### ISSUE TITLE
附件上传问题

### ISSUE THREAD

**Issue by Linuzs** [zmister2016/MrDoc#34]
当前版本0.6.0
docker版本
附件上传提示“请求上传接口出现异常”，请问是什么原因
![image](https://user-images.githubusercontent.com/20413003/99025356-91be5900-25a3-11eb-84d9-8a292bb8ec90.png)

**Comment by zmister2016** [comment]
@Linuzs 检查一下附件上传文件格式的配置

**Comment by Linuzs** [comment]
默认是.zip格式我试过了也不行。配置文件没动过，上传时日志显示服务器响应500。（docker版镜像）

**Comment by zmister2016** [comment]
0.6.1 版本已修复
