### ISSUE TITLE
渲染出来的代码复制后会丢失空行，影响代码分块

### ISSUE THREAD

**Issue by ijustyce** [zmister2016/MrDoc#35]
我一直在寻找开源的 wiki 和 笔记，Mrdoc 的确很简洁，很喜欢。但是，该有的通病同样有。比如：
```
import datetime

print(datetime.date.today())
```
这样的代码块，很多类似的项目复制后都会丢失中间的空白行，变为如下：
```
import datetime
print(datetime.date.today())
```
这让本来写的很好的代码，一下子失去了分块，体验不好。能否做下优化。我只是一个后端，前端不懂，不知为啥绝大多数开源wiki和笔记都有这个问题。

**Comment by zmister2016** [comment]
@ijustyce 猜测你使用的应该是在Editor.md编辑器模式编写的文档，可以尝试一下Vditor编辑器模式。个人测试在Vditor编辑器模式下，示例代码的复制不会出现你所说的问题。

编辑器的修改在“个人中心 > 个人设置”里面。

至于绝大多数开源wiki都有这个问题，其原因是大部分的项目使用的都是开源的Editor.md编辑器，而这个编辑器已经停更很久了，很多Bug也没有修复。

**Comment by ijustyce** [comment]
@zmister2016 多谢，我之前是看你的演示站点发现的，刚才自己跑了个。完美。感谢。
