### ISSUE TITLE
增加互动功能：点赞、评论、回复等；  增加“我的收藏”。

### ISSUE THREAD

**Issue by zyy2721** [zmister2016/MrDoc#39]
1、互动功能：
希望能在每篇文章后添加一个点赞、评论、回复的功能，方便技术交流。
2、收藏功能：
希望能新增一个收藏功能，方便通过 ”我的收藏“ 快速查看文档。

**Comment by zmister2016** [comment]
@zyy2721 感谢你的建议，后续将评估之后根据计划安排相应的功能开发

**Comment by yanghe1117** [comment]
支持，希望能增加

**Comment by zmister2016** [comment]
@zyy2721 已有文集和文档的收藏功能。文档评论功能在专业版中支持，如需了解详情，可加QQ：3280350050
