### ISSUE TITLE
开发者入伙

### ISSUE THREAD

**Issue by jeeyshe** [zmister2016/MrDoc#5]
之前我和楼主想法一样，准备使用django + gitbook构建一个文档网站，后来忙起来就搁置了，让我成为维护者吧，我２年后端开发，看看还要些啥条件的（头条上看到这个项目的）

**Comment by zmister2016** [comment]
@jeeyshe 首先感谢你对MrDoc的认可。目前MrDoc还没有清晰的规划，还在做一些前期性的开发，如果可以，欢迎加MrDoc的QQ群交流，群号是735507293，密码mrdoc
