### ISSUE TITLE
发现私密文集游客可搜索

### ISSUE THREAD

**Issue by molezz** [zmister2016/MrDoc#50]
docker部署方式，新建第一个私密文集，新建文档。
以游客模式可以搜索到该文档和摘要
0.6.2版本，看了下今天docker pull jonnyan404/mrdoc-alpine下来的，菜单提示0.6.2而不是3

**Comment by zmister2016** [comment]
@molezz 已知悉，感谢反馈，修复好了会通知的。

**Comment by zmister2016** [comment]
@molezz 问题已修复，docker版本可能会延迟
