### ISSUE TITLE
左右区域的同步滚动在Markdown中有多张图片时严重错位

### ISSUE THREAD

**Issue by line-bear** [zmister2016/MrDoc#52]
当Markdown中插入很多图片后，preview区域和edit区域会严重错位，当前编辑区的内容会跑到预览的下一页。
可以参考 
https://maxiang.io/
https://stackedit.io/editor 
的实现

实现起来可能相对困难，但希望先提供一个能取消同步滚动的接口，不然就只能反复滚动降低效率。

跟下面的这个issues是相同的问题，属于editor.md的遗留问题了。
https://github.com/pandao/editor.md/issues/56

**Comment by zmister2016** [comment]
确实是属于 EditorMD 的遗留问题，目前暂时不准备对 EditorMD 的 Bug 进行处理，后期会重新维护一个 EditorMD 的版本。如果实在影响书写体验，可以切换一下编辑器试试 Vditor 编辑器。

**Comment by line-bear** [comment]
> 确实是属于 EditorMD 的遗留问题，目前暂时不准备对 EditorMD 的 Bug 进行处理，后期会重新维护一个 EditorMD 的版本。如果实在影响书写体验，可以切换一下编辑器试试 Vditor 编辑器。

看了一下EditorMD的源码，发现即使是按百分比滚动，也存在相应的问题。
1. 滚动比例的计算方式不对，不应该是滚动高直接除以总高，应改成 滚动高/(总高-可视高)
2. `preview.scrollTop((preview[0].scrollHeight  + tocHeight + tocMenuHeight) * percent);` 这里重复计算了[TOC]和[TOCM]的高度，我想作者的初衷可能是想要缩小由于目录导致的错位差异，但是会导致某侧已经滚动到底部了，另外一侧还有10%左右没有滚动完。

针对以上问题，在这里提出了几点临时解决方案：
1. 完全按照比例进行同步滚动，这样做至少如果某个章节有错位，后续章节会慢慢同步回来，不会越错越离谱。
2. 编辑区最后剩下的空白行也需要解析，或者不算在滚动区域里。
3. 编辑方式可以设置成single，即编辑区->预览区 单向绑定 `editor.config("syncScrolling", "single");`

同步滚动修改后的源码(完全按照比例进行同步滚动)：
`
         /**
         * 绑定同步滚动
         * 
         * @returns {editormd} return this
         */
        
        bindScrollEvent : function() {
            
            var _this            = this;
            var preview          = this.preview;
            var settings         = this.settings;
            var codeMirror       = this.codeMirror;
            var mouseOrTouch     = editormd.mouseOrTouch;
            
            if (!settings.syncScrolling) {
                return this;
            }
                
            var cmBindScroll = function () {
                
                codeMirror.find(".CodeMirror-scroll").bind(mouseOrTouch("scroll", "touchmove"), function (event) {
                    var scrollTop = $(this).scrollTop();
                    var percent = (scrollTop / ($(this)[0].scrollHeight - this.clientHeight));

                    preview.scrollTop((preview[0].scrollHeight - preview[0].clientHeight) * percent);

                    console.log("preview[0].height" + preview[0].clientHeight);
                    $.proxy(settings.onscroll, _this)(event);
                });

            };

            var cmUnbindScroll = function () {
                codeMirror.find(".CodeMirror-scroll").unbind(mouseOrTouch("scroll", "touchmove"));
            };

            var previewBindScroll = function () {

                preview.bind(mouseOrTouch("scroll", "touchmove"), function (event) {
                    var scrollTop = $(this).scrollTop();
                    var percent = (scrollTop / ($(this)[0].scrollHeight - this.clientHeight));
                    var codeView = codeMirror.find(".CodeMirror-scroll");

                    codeView.scrollTop((codeView[0].scrollHeight - codeView[0].clientHeight) * percent);

                    $.proxy(settings.onpreviewscroll, _this)(event);
                });

            };`

有条件最好还是按照章节进行同步滚动，效果最好，主要还是怎么获取到当前最靠近顶部的章节名称，再获取到对应渲染的html element，剩下的还是和上面一样的绑定滚动，只不过内容更加细分了。还可以更简单粗暴直接调用scrollIntoView。

**Comment by zmister2016** [comment]
嗯，后续测试一下，如果没问题，可以作为临时的解决方案。感谢！

**Comment by zmister2016** [comment]
最新代码已重构Editormd编辑器，将归版至0.9.5
