### ISSUE TITLE
文档下载导出

### ISSUE THREAD

**Issue by leebeep** [zmister2016/MrDoc#53]
1、后台可以看到导出电子书、pdf，但是实际并不能
2、可以看入word，但是无法导出word

目前功能都很齐全，博主非常优秀。希望能优先把导入导出搞靓，那就是真的好了。

**Comment by zmister2016** [comment]
pdf 导出目前依赖于 Chromium，需要安装之后再进行配置。后面的版本会用 PyQt5 进行替代，直接可用。

**Comment by leebeep** [comment]
非常感谢答复，我试了一下，生成pdf一直是转圈圈的状态。因为没有时间专门研究源码所以不知道原因，所以在这里贴一下。
![111111](https://user-images.githubusercontent.com/42606346/104569980-5405ab80-568c-11eb-9e04-bf5bfae5bdc0.JPG)

**Comment by FrankZhangCN** [comment]
类似的问题。
一开始提示“生成出错”，error.log显示缺少atk，gtk等so文件，安装后，提示chrome不能使用root启动。把启动配置改成www-data后，仍然有问题。
此时，圈圈转了很久，就提醒一个“服务器异常”，error.log无错误日志。这个时候要怎么去找哪里出错了呢。。。。

**Comment by FrankZhangCN** [comment]
systemctl status下看到相关错误：
coroutine 'Browser._targetCreated' was never awaited

查询后，有相关问题：https://github.com/pyppeteer/pyppeteer/issues/179

按照说法，对pyppeteer升级即可。我的阿里云ubuntu20里面是python3.8+pyppeteer0.0.25
将pyppeteer改为0.2.2后，systemctl restart后可以了。

**Comment by zmister2016** [comment]
PDF导出功能在0.6.5版本已调整方案，稳定性有较大的提高
