### ISSUE TITLE
更新v0.6.3 点协作人报500

### ISSUE THREAD

**Issue by ghostman-git** [zmister2016/MrDoc#54]
v0.6.3

管理员登录

![image](https://user-images.githubusercontent.com/13376074/103765014-74fc4a00-5057-11eb-9b0b-eb36cb183ccd.png)

![image](https://user-images.githubusercontent.com/13376074/103765040-7ded1b80-5057-11eb-90c7-4df455317b01.png)

**Comment by zmister2016** [comment]
我这边在本地和示例网站上测试都是正常的。0.6.3涉及到了数据库表的变动，不知道是否执行了数据库迁移命令？GitHub上的图片我这边网络显示不了，暂时不好判断。

**Comment by ghostman-git** [comment]
> 我这边在本地和示例网站上测试都是正常的。0.6.3涉及到了数据库表的变动，不知道是否执行了数据库迁移命令？GitHub上的图片我这边网络显示不了，暂时不好判断。

现在docker升级不需要手动执行脚本了吧？    发现只有管理员报错，个人登录没问题。

**Comment by Jonnyan404** [comment]
> > 我这边在本地和示例网站上测试都是正常的。0.6.3涉及到了数据库表的变动，不知道是否执行了数据库迁移命令？GitHub上的图片我这边网络显示不了，暂时不好判断。
> 
> 现在docker升级不需要手动执行脚本了吧？ 发现只有管理员报错，个人登录没问题。

最好贴下你访问这个页面相关的报错日志,,,`docker logs mrdoc`可以获取日志

**Comment by zmister2016** [comment]
@ghostman-git 如果是管理员为非自己创建的文集添加协作时出现的500，那么这个问题在最新代码中已经修复

**Comment by ghostman-git** [comment]
> @ghostman-git 如果是管理员为非自己创建的文集添加协作时出现的500，那么这个问题在最新代码中已经修复

收到

**Comment by Jonnyan404** [comment]
> > @ghostman-git 如果是管理员为非自己创建的文集添加协作时出现的500，那么这个问题在最新代码中已经修复
> 
> 收到

正在重新打包中，，，也可以自行进容器内 git pull  ，然后重启
