### ISSUE TITLE
图片上传不能正确显示

### ISSUE THREAD

**Issue by caijian76** [zmister2016/MrDoc#57]
首先，非常感谢你的付出，给我们带来怎么好的系统。我在使用中发现一个BUG：
版本：0.6.3
现象：上传图片成功，但是在文档中引用，不能正常显示。
情况：图片的文件名中，含有空格的都有以上问题。

在MAC下，很多系统截图的图片，文件名中都含有空格。如：“截屏2020-09-15 上午12.00.03.png”，希望能解决。谢谢。

**Comment by zmister2016** [comment]
@caijian76 最新代码已修复图片名称包含空格时引用不显示的问题
