### ISSUE TITLE
建议增加登录验证码功能

### ISSUE THREAD

**Issue by ht4266394** [zmister2016/MrDoc#59]
建议师傅增加登陆验证码功能防止破暴力破解的风险，一般都会放到公网上，如果没有验证码就可以一直爆破，一来有风险二来莫名就增加了服务器的负载，希望采纳，谢谢

**Comment by Jonnyan404** [comment]
同时建议集成 Google 2FA 认证

**Comment by zmister2016** [comment]
@ht4266394 最新代码已添加此功能，将归版至`0.6.5`
