### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by 81724097** [zmister2016/MrDoc#6]
不知是我操作问题还是
在执行git pull
发现即使做migrate
仍然是个全新的环境
原来内容都不见了 ;(!

**Comment by zmister2016** [comment]
能否详细说明一下

**Comment by 81724097** [comment]
就是给git pull以后原来的数据文档都没有了。像一个全新系统

**Comment by zmister2016** [comment]
@81724097 0.5.1版本调整了项目目录，如果使用的sqlite，其调用的就是config目录下的数据库文件了，不再是之前项目根路径下的数据库文件
