### ISSUE TITLE
管理员退出登陆时会导致重定向过多，服务器500错误

### ISSUE THREAD

**Issue by ht4266394** [zmister2016/MrDoc#63]
![image](https://user-images.githubusercontent.com/77309026/107135219-c425eb00-6933-11eb-83b3-39febcd80cd9.png)
需要手动刷新，刷新后正常

**Comment by zmister2016** [comment]
实测管理员退出登录会停留在当前页面，并报`403`提示无权限，未发现500错误

**Comment by ht4266394** [comment]
> 实测管理员退出登录会停留在当前页面，并报`403`提示无权限，未发现500错误

师傅，我测试的后台和其他页面测试正常，是在首页的情况下点退出会出现无法返回主页的情况，你试一下。

**Comment by zmister2016** [comment]
> > 实测管理员退出登录会停留在当前页面，并报`403`提示无权限，未发现500错误
> 
> 师傅，我测试的后台和其他页面测试正常，是在首页的情况下点退出会出现无法返回主页的情况，你试一下。

在示例站点`mrdoc.zmister.com`测试，首页退出也是正常回到首页的。
