### ISSUE TITLE
优化左侧目录的建议

### ISSUE THREAD

**Issue by ht4266394** [zmister2016/MrDoc#64]
建议优化文集内左侧目录的效果，点击文字链接时才会进入该页面，点击其他空白地方时都是默认展开下层目录。在使用过程中更多的时候是需要展开目录，目前只能通过栏目上右侧特别小的三角才能展开折叠，使用起来不是特别的顺手方便，希望采纳。

**Comment by zmister2016** [comment]
@ht4266394 参考了一下其他的文档系统，点击空白和点击图标控制目录收起/展开的都有，暂时不考虑替换了
