### ISSUE TITLE
vditor编辑器左侧大纲无法显示

### ISSUE THREAD

**Issue by wpwbb510582246** [zmister2016/MrDoc#70]
如图，最新代码中vditor编辑器左侧大纲无法显示
<img width="1280" alt="未命名" src="https://user-images.githubusercontent.com/22250741/109474555-9b66c080-7aaf-11eb-9ae8-400d24d4457b.png">

**Comment by zmister2016** [comment]
@wpwbb510582246 在Windows下测试，是能够正常显示的：

![image](https://user-images.githubusercontent.com/42526859/111865050-a8d0e580-899f-11eb-865c-c0d3f55c7074.png)

**Comment by wpwbb510582246** [comment]
> @wpwbb510582246 在Windows下测试，是能够正常显示的：
> 
> ![image](https://user-images.githubusercontent.com/42526859/111865050-a8d0e580-899f-11eb-865c-c0d3f55c7074.png)

现在已经可以了
