### ISSUE TITLE
使用frp内网穿透部署项目时生成网站地图的地址不对

### ISSUE THREAD

**Issue by wpwbb510582246** [zmister2016/MrDoc#72]
项目采用frp内网穿透映射远程主机的项目，生成的网站地图的地址为frp服务器内网穿透的地址，可以将其改为网站的域名吗？
<img width="1277" alt="2021-03-10_10-47-35" src="https://user-images.githubusercontent.com/22250741/110568791-8b756d80-818e-11eb-8b63-9cd39f4210cb.png">

**Comment by zmister2016** [comment]
@wpwbb510582246 试试启动项目使用本机IP地址0.0.0.0而非127.0.0.1

**Comment by wpwbb510582246** [comment]
> @wpwbb510582246 试试启动项目使用本机IP地址0.0.0.0而非127.0.0.1

![image](https://user-images.githubusercontent.com/22250741/112262309-6d3c6100-8ca8-11eb-824c-90b90c4c87c1.png)
启动项目时用的就是0.0.0.0

**Comment by wpwbb510582246** [comment]
我明白了，这是因为nginx里面的配置写的不对，修改一下既可以了。
![image](https://user-images.githubusercontent.com/22250741/113669835-e7c4a200-96e6-11eb-87b0-ff18bf12ac9f.png)
![image](https://user-images.githubusercontent.com/22250741/113669879-f4e19100-96e6-11eb-9481-afc3752d218b.png)
