### ISSUE TITLE
文档详情页面右侧大纲有数据却无法显示出来

### ISSUE THREAD

**Issue by wpwbb510582246** [zmister2016/MrDoc#73]
文档详情页面右侧大纲有数据却无法显示出来，推测是因为右侧大纲的背景颜色将大纲内容遮盖了
![image](https://user-images.githubusercontent.com/22250741/110572861-35f08f00-8195-11eb-8b5c-093f7b1ff72d.png)

**Comment by zmister2016** [comment]
@wpwbb510582246 最新代码已修复，将归版至0.6.6
