### ISSUE TITLE
允许只读用户搜索文档

### ISSUE THREAD

**Issue by zyy2721** [zmister2016/MrDoc#82]
在实际应用过程中，会有一些用户被限制 “只读”权限，即没有文集的协作权限。但他们又需要通过搜索来定位文档。
希望可以增加只读用户搜索文档的功能。

**Comment by zmister2016** [comment]
@zyy2721 文集是否协作，取决于是否添加了文集成员；文集内的文档是否可被搜索和查看，取决于文集的权限（私密、公开、指定用户、访问码）；这样能理解吧？
