### ISSUE TITLE
正文链接中若出现全文搜索的关键字，链接失效

### ISSUE THREAD

**Issue by eternalhook** [zmister2016/MrDoc#85]
全文搜索的关键字，如在正文的url中出现并被高亮后，原有链接无法访问到目标站点

**Comment by zmister2016** [comment]
@eternalhook 已知悉，将在下一版本修复

**Comment by zmister2016** [comment]
@eternalhook 搜索词高亮导致代码块和链接异常的问题最新代码已修复，将归版至 0.6.7 版本，感谢反馈！
