### ISSUE TITLE
文集导出一直处于导出状态

### ISSUE THREAD

**Issue by sizuichu** [zmister2016/MrDoc#90]
导出文集时，一直在加载状态，数量40
![Snipaste_2021-05-28_23-36-11](https://user-images.githubusercontent.com/36018846/120008521-9b725000-c00d-11eb-9538-3838f855d55a.png)
+篇

**Comment by zmister2016** [comment]
已知悉，后续会进行测试排查，感谢反馈

**Comment by zmister2016** [comment]
@sizuichu 这个现在解决了吗？

**Comment by sizuichu** [comment]
已更新得到解决，谢谢
