### ISSUE TITLE
Translation to English/Spanish

### ISSUE THREAD

**Issue by javrodsan5** [zmister2016/MrDoc#94]
Are you planning to develop an option in which MrDoc is available in English or Spanish?

**Comment by zmister2016** [comment]
Currently, it supports the configuration of English language.You can configure the value of `language` to 'en' under `locale` in the `config/config.Ini` file.But translation is not manual translation, the accuracy is not very high.
—— The above is from Google translation.

**Comment by javrodsan5** [comment]
Ok, thank you very much!
