### ISSUE TITLE
主题切换

### ISSUE THREAD

**Issue by wpwbb510582246** [zmister2016/MrDoc#95]
可以增加一个主题切换的功能吗，感觉明亮的主题长时间看的话有点刺眼。
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/22250741/121792607-e43f2100-cc29-11eb-955b-29bcad8ad1af.png">
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/22250741/121792610-e903d500-cc29-11eb-8d0a-2a623efb720b.png">

**Comment by zmister2016** [comment]
这个直接通过浏览器的主题切换就好了
